# Generated by Django 4.0.4 on 2022-08-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Author_Name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
