# Generated by Django 4.0.4 on 2022-08-03 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_upcoming'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upcoming',
            options={'verbose_name_plural': 'upcoming'},
        ),
    ]
