# Generated by Django 4.0.4 on 2022-08-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_email_orders_address_rename_games_orders_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('t1', models.CharField(max_length=200)),
                ('t2', models.CharField(max_length=200)),
                ('t3', models.CharField(max_length=200)),
                ('t4', models.CharField(max_length=200)),
            ],
        ),
    ]
