# Generated by Django 4.0.4 on 2022-08-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.TextField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
