# Generated by Django 4.0.4 on 2022-08-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=111)),
                ('email', models.CharField(max_length=111)),
                ('message', models.TextField(max_length=11111)),
                ('phone', models.IntegerField()),
                ('games', models.CharField(max_length=111)),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'books'},
        ),
        migrations.AddField(
            model_name='product',
            name='populer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='top',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='tranding',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(max_length=200000),
        ),
    ]
