# Generated by Django 4.0.4 on 2022-08-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_upcoming_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=111)),
                ('email', models.CharField(max_length=111)),
                ('phone', models.ImageField(upload_to='')),
                ('subject', models.CharField(max_length=111)),
                ('message', models.TextField(max_length=11111)),
            ],
            options={
                'verbose_name_plural': 'contact',
            },
        ),
    ]
