# Generated by Django 4.0.4 on 2022-08-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_contact_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='email',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='games',
            new_name='Book',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='name',
            new_name='City',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='message',
        ),
        migrations.AddField(
            model_name='orders',
            name='Firstname',
            field=models.CharField(default=1, max_length=111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='Lastname',
            field=models.CharField(default=1, max_length=111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='State',
            field=models.CharField(default=1, max_length=111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='Zip_code',
            field=models.CharField(default=1, max_length=111),
            preserve_default=False,
        ),
    ]
