# Generated by Django 4.0.4 on 2022-08-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=111)),
                ('work', models.CharField(max_length=111)),
                ('desc', models.TextField(max_length=2000)),
            ],
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': 'slider'},
        ),
        migrations.AlterField(
            model_name='slider',
            name='img',
            field=models.ImageField(help_text='use png image', upload_to='pics'),
        ),
    ]
