# Generated by Django 4.0.4 on 2022-08-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_testimonials_alter_slider_options_alter_slider_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Working',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=111)),
                ('post', models.CharField(max_length=111)),
                ('img', models.ImageField(help_text='use png image', upload_to='pics')),
            ],
        ),
    ]
