# Generated by Django 4.0.4 on 2022-08-09 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_working'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Firstname',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='Lastname',
            new_name='name',
        ),
    ]
